$(document).ready(function() {
$("#form1").validate({
    rules:{ nis:{required:true,number: true}, 
			nama:"required",
			kelas:"required",
			jenis_kelamin:"required",
			tgl_lahir:"required", 
            no_telp:{required:true,number: true},      
            alamat:"required",
			nama_mapel:"required",
			tingkat:"required",
			modul:"required",
			password:"required",
			konfirmasi:"required",
			level:"required",
			kode_mapel:"required",
			pertanyaan:"required",
			pilihan_a:"required",
			pilihan_b:"required",
			pilihan_c:"required",
			pilihan_d:"required",
			kunci_jawaban:"required",
			judul_topik:"required",
			isi_pesan:"required",
			pertemuan:{required:true,number: true}, 
          },
    messages:{ 
			nis:{
                required:'NIS harus diisi',
                number  :'Hanya boleh diisi Angka'},
            nama:{required:'Nama harus diisi'},
			kelas:{required:'Kelas harus diisi'},
			jenis_kelamin:{required:'Jenis Kelamin harus diisi'},
            tgl_lahir:{required:'Tanggal harus diisi'},
			no_telp:{
                required:'No Telp harus diisi',
                number  :'Hanya boleh diisi Angka'},
            alamat: {required:'Alamat harus diisi'},
			 nama_mapel:{required:'Nama Mata Pelajaran harus diisi'},
			 tingkat:{required:'Tingkat harus diisi'},
			 modul:{required:'Modul harus di Upload'},
			 password:{required:'Password harus diisi'},
			 konfirmasi:{required:'Konfirmasi harus diisi'},
			 level:{required:'Akses Level harus diisi'},
			  kode_mapel:{required:'Kode Soal harus diisi'},
			  pertanyaan:{required:'Pertanyaan harus diisi'},
			  pilihan_a:{required:'Pilihan A harus diisi'},
			  pilihan_b:{required:'Pilihan B harus diisi'},
			  pilihan_c:{required:'Pilihan C harus diisi'},
			  pilihan_d:{required:'Pilihan D harus diisi'},
			  kunci_jawaban:{required:'Kunci Jawaban harus diisi'},
			  judul_topik:{required:'Judul harus diisi'},
			  isi_pesan:{required:'Pesan harus diisi'},
			 pertemuan:{
                required:'Pertemuan harus diisi',
                number  :'Hanya boleh diisi Angka'},
            },
     success: function(label) {
        label.text('Benar').addClass('valid');}
    });
});